#!/usr/bin/env node
/**
 * Extracts a curated Lucide subset into `src/host/icon-data.ts`.
 *
 * Generated and COMMITTED, rather than resolved out of `node_modules` at
 * request time the way `ui-runtime.ts` resolves htm. That divergence is about
 * size and nothing else: htm is 13 KB, so reading it at runtime costs a
 * dependency nobody notices, while `lucide-static` is **65 MB for 2,112
 * icons** and an applet needs about fifty. Putting that in `dependencies`
 * makes every user of Bernard install 65 MB to draw a magnifying glass.
 *
 * So the package is a devDependency, this script lifts what we serve, and the
 * result is a plain TypeScript module — which also means it works identically
 * under `tsx` and in a global install, with no dist layout to depend on and no
 * copy step to forget. That is the property `ui-runtime.ts` values in runtime
 * resolution, reached a different way.
 *
 * Re-run with `npm run generate-icons`. `icons.drift.test.ts` fails if the
 * committed file stops matching the installed package, so this cannot rot
 * silently.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const root = path.dirname(fileURLToPath(import.meta.url));

/**
 * What an applet actually needs.
 *
 * Curated, not the whole set: every name here is a promise to a model, and a
 * catalogue of 2,112 is one nobody can hold in a prompt. Familiar icons for
 * familiar actions — trash for delete, gear for settings, magnifying glass
 * for search — and nothing whose meaning has to be decoded.
 */
export const ICON_NAMES = [
  // Actions
  'plus', 'minus', 'x', 'check', 'search', 'filter', 'refresh-cw',
  'download', 'upload', 'save', 'trash-2', 'pencil', 'copy',
  'external-link', 'settings', 'more-horizontal',
  // Navigation
  'chevron-right', 'chevron-left', 'chevron-up', 'chevron-down',
  'arrow-right', 'arrow-left', 'menu', 'house',
  // Status
  'circle-check', 'circle-alert', 'triangle-alert', 'info', 'circle-x',
  'loader-circle',
  // Things
  'file-text', 'folder', 'calendar', 'clock', 'user', 'users', 'mail',
  'link', 'star', 'bookmark', 'tag', 'list', 'layout-grid', 'database',
  'globe', 'image', 'play', 'pause', 'eye', 'eye-off', 'lock', 'bell',
];

const pkgRoot = path.dirname(require.resolve('lucide-static/package.json'));
const { version, license } = JSON.parse(
  fs.readFileSync(path.join(pkgRoot, 'package.json'), 'utf-8'),
);

/** The drawing commands only: everything inside `<svg>`, whitespace collapsed. */
function innerMarkup(name) {
  const file = path.join(pkgRoot, 'icons', `${name}.svg`);
  const raw = fs.readFileSync(file, 'utf-8');
  const body = raw.slice(raw.indexOf('>', raw.indexOf('<svg')) + 1, raw.lastIndexOf('</svg>'));
  const collapsed = body.replace(/\s+/g, ' ').trim();
  if (!collapsed) throw new Error(`${name}.svg produced no markup`);
  // A child's own `width`/`height` is shape geometry (`<rect width="18">`) and
  // is fine — the root's were already stripped with the opening tag. What must
  // not appear is a per-icon `stroke-width`, which would break the consistent
  // visual weight the whole set is chosen for, or a nested `<svg>`, which
  // would carry its own coordinate system past the wrapper.
  if (/stroke-width=/.test(collapsed) || /<svg/i.test(collapsed)) {
    throw new Error(`${name}.svg overrides the wrapper's stroke or viewBox`);
  }
  return collapsed;
}

const entries = [...ICON_NAMES].sort().map((n) => [n, innerMarkup(n)]);

const out = `// GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Re-run with \`npm run generate-icons\`; \`icons.drift.test.ts\` pins it.
//
// Lucide ${version}, ${license}. https://lucide.dev
// Path data only; the wrapper in \`icons.ts\` supplies viewBox, stroke and size,
// which is what keeps stroke weight and optical size identical across the set.

/** Inner SVG markup per icon, keyed by name. Every icon is a 24x24 viewBox. */
export const ICON_PATHS: Readonly<Record<string, string>> = Object.freeze({
${entries.map(([n, m]) => `  ${JSON.stringify(n)}: ${JSON.stringify(m)},`).join('\n')}
});

/** Upstream version the committed data was lifted from. */
export const LUCIDE_VERSION = ${JSON.stringify(version)};
`;

const dest = path.join(root, '..', 'src', 'host', 'icon-data.ts');
fs.writeFileSync(dest, out);
console.log(`wrote ${entries.length} icons from lucide-static@${version} -> ${path.relative(path.join(root, '..'), dest)}`);
